language: python
python:
  - "2.7"
  - "3.4"
env:
  global:
  - APT_DEPENDENCIES="doxygen doxygen-latex libltdl-dev libboost-all-dev liblog4cxx10-dev coinor-libipopt-dev libblas-dev liblapack-dev libmumps-seq-dev gfortran"
  - GIT_DEPENDENCIES="roboptim/roboptim-core roboptim/roboptim-core-plugin-ipopt"
  - GH_USERNAME=thomas-moulard
  - GH_REPO=roboptim/roboptim-core-python
  - LCOV_IGNORE_RULES="*tests*"
  - secure: "Slm+HqRT+Vy0SG7E9gEShuHvNz6XWRUmBhVBLVJEaYy/0Lo2qp4OjFEWDjiJwFIiXstW2Wclds4SuewAn3Tc4x7dsY+5uaMCX7S/HPzsBCjLXUwjKasUqEGaVTIYmtFJm57hOkz6K2SLUUV4intkMiwtCiq/R0xe92QTTKkHyfo="
notifications:
  email:
    - roboptim@googlegroups.com
branches:
  only:
    - master
    - travis
before_install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo apt-get update -q
  - sudo apt-get install python${TRAVIS_PYTHON_VERSION}-dev
  - pip install matplotlib
  - ./.travis/dependencies/eigen-3.2
  - ./.travis/run before_install
script:
  - export PYTHON_INCLUDE_DIR="`find /usr/include -name Python.h -printf '%h\n' | grep \"python${TRAVIS_PYTHON_VERSION}\"`"
  - export CMAKE_ADDITIONAL_OPTIONS="-DPython_ADDITIONAL_VERSIONS=${TRAVIS_PYTHON_VERSION} -DPythonLibs_FIND_VERSION=${TRAVIS_PYTHON_VERSION} -DPYTHON_EXECUTABLE=${VIRTUAL_ENV}/bin/python -DPYTHON_LIBRARY=${VIRTUAL_ENV}/lib/libpython${TRAVIS_PYTHON_VERSION}.so -DPYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIR} -DPYTHON_PACKAGES_PATH=${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/"
  - export LD_LIBRARY_PATH="/tmp/_travis/install/lib/roboptim-core/"
  - ./.travis/run build
after_success:
  # Print Ipopt logs even after success
  - . .travis/common.sh
  - "find $build_dir/tests -name \"*.log\" | xargs -i sh -c \"echo '####### Printing content of {} ######'; cat {}\""
  # Fix for coveralls upload
  - export CC=gcc
  - ./.travis/run after_success
after_failure: ./.travis/run after_failure
